import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/src/components/lib/utils";
import { Toaster } from "@/src/components/ui/sonner";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={cn("font-sans", inter.variable)}>
      <body>
        <div className="min-h-screen bg-gray-50">
          <header className="border-b border-gray-200 bg-white">
            <div className="mx-auto flex h-14 max-w-4xl items-center px-4">
              <a href="/users" className="text-sm font-bold text-gray-900 hover:text-blue-600">
                Sensedia Challenge
              </a>
            </div>
          </header>

          <main className="mx-auto max-w-4xl px-4 py-8">{children}</main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
